name = "SubtitleStretcher"
uuid = "2d1ea495-59ca-4a67-a095-ac91cc6f6b4b"
authors = ["cormullion <cormullion@mac.com> and contributors"]
version = "0.2.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
